# Generated by Django 4.2.16 on 2025-05-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('accounts', '0003_customuser_interestbook_alter_customuser_followings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='interestBook',
        ),
        migrations.AddField(
            model_name='customuser',
            name='interestBook',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='books.book'),
        ),
    ]
