# Generated by Django 4.2.16 on 2025-05-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_interestbook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
