# Generated by Django 4.2.16 on 2025-05-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
