# Generated by Django 4.2.16 on 2025-05-27 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='interestBook',
            new_name='interestBooks',
        ),
    ]
