# Generated by Django 4.2.16 on 2025-05-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('accounts', '0007_rename_interestbook_customuser_interestbooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='read_books',
            field=models.ManyToManyField(blank=True, related_name='read_users', to='books.book'),
        ),
    ]
