# Generated by Django 4.2.16 on 2025-05-26 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0003_comment_created_at_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='like_users',
            field=models.ManyToManyField(related_name='like_thread', to=settings.AUTH_USER_MODEL),
        ),
    ]
