# Generated by Django 4.2.16 on 2025-05-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_thread_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='community.hashtag'),
        ),
    ]
