# Generated by Django 4.2.16 on 2025-05-23 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('isbn', models.IntegerField()),
                ('cover', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=30)),
                ('pub_date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('author_info', models.TextField()),
                ('author_photo', models.CharField(max_length=255)),
                ('customer_review_rank', models.FloatField()),
                ('subTitle', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category')),
            ],
        ),
    ]
