# Generated by Django 4.2.16 on 2025-05-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='voice_file',
            field=models.FileField(blank=True, null=True, upload_to='voice/'),
        ),
    ]
